apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaugamela
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5002"
spec:
  replicas: 2x
  selector:
    matchLabels:
      app: gaugamela
  template:
    metadata:
      labels:
        app: gaugamela
    spec:
      containers:
      - name: gaugamela
        image: 192.168.86.39:30500/gaugamela:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"